services:
  frontend:
    build:
      context: ./projectXF
      dockerfile: Dockerfile
    image: ${FRONTEND_IMAGE}
    ports:
      - "0.0.0.0:${FRONTEND_PORT}:80"
      - "[::]:${FRONTEND_PORT}:80"
    networks:
      - production_network
    environment:
      - BACKEND_URL=http://backend:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./projectXB
      dockerfile: Dockerfile
    image: ${BACKEND_IMAGE}
    ports:
      - "0.0.0.0:${BACKEND_PORT}:${BACKEND_PORT}"
      - "[::]:${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - NODE_ENV=production
    networks:
      - production_network

networks:
  production_network:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd00::/80