name: projectx

services:
  frontend:
    container_name: projectxf_container
    build: ./projectXF
    image: ${FRONTEND_IMAGE}
    ports:
      - '0.0.0.0:80:80'
    networks:
      - app-network

  backend:
    container_name: projectxb_container
    build: ./projectXB
    image: ${BACKEND_IMAGE}
    ports:
      - '0.0.0.0:3000:3000'
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  app-network:
    driver: bridge