name: projectx

services:
  frontend:
    container_name: projectxf_container
    build: ./projectXF
    image: ${FRONTEND_IMAGE}
    ports:
      - '0.0.0.0:80:80'
    networks:
      - app-network

  backend:
    container_name: projectxb_container
    build: ./projectXB
    image: ${BACKEND_IMAGE}
    ports:
      - '0.0.0.0:3000:3000'
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGO_URL=mongodb://mongodb:27017/projectx

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: