services:
  frontend:
    container_name: projectxf_container
    build: ./projectXF
    image: ${FRONTEND_IMAGE}
    ports:
      - '0.0.0.0:4200:4200'
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:3000
    networks:
      - app-network

  backend:
    container_name: projectxb_container
    build: ./projectXB
    image: ${BACKEND_IMAGE}
    ports:
      - '0.0.0.0:3000:3000'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge