---
- name: Deploy ProjectX on Raspberry
  hosts: raspberry
  become: true

  vars:
    project_dir: /projectX
    FRONTEND_IMAGE: pedroaccarini/projectxf:latest
    BACKEND_IMAGE: pedroaccarini/projectxb:latest
    MONGO_IMAGE: mongo:latest
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name:
          - docker.io
          - python3-pip
          - python3-setuptools
          - git
        state: present
    
    - name: Create project directory
      file:
        path: "{{ project_dir }}"
        state: directory

    - name: Clone project repository of ProjectX
      git:
        repo: https://github.com/P4dr4/ProjectX.git
        dest: "{{ project_dir }}"

    - name: Run docker-compose up -d
      command: docker-compose -f "{{ project_dir }}/docker-compose.yml" up -d
      args:
        chdir: "{{ project_dir }}"