---
- name: Deploy ProjectX on Raspberry
  hosts: raspberry
  become: true

  vars:
    project_dir: /projectX
    FRONTEND_IMAGE: pedroaccarini/projectxf:latest
    BACKEND_IMAGE: pedroaccarini/projectxb:latest
    MONGO_IMAGE: mongo:latest

  pre_tasks:
    - name: Install required packages
      apt:
        name: 
          - python3
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

  tasks:
    - name: Create ProjectX directory
      file:
        path: "{{ project_dir }}"
        state: directory
        mode: '0755'

    - name: Clone ProjectX repository
      git:
        repo: "https://github.com/P4dr4/projectX.git"
        dest: "{{ project_dir }}"
        force: yes

    - name: Docker-Compose Build
      command: docker-compose build --env-file .env
      args:
        chdir: "{{ project_dir }}"

    - name: Docker-Compose Up
      command: docker-compose up -d
      args:
        chdir: "{{ project_dir }}"
      environment:
        FRONTEND_IMAGE: "{{ FRONTEND_IMAGE }}"
        BACKEND_IMAGE: "{{ BACKEND_IMAGE }}"
        MONGO_IMAGE: "{{ MONGO_IMAGE }}"
