---

- name: Build and Push Docker Images
  hosts: raspberry

  vars:
    backend_image: "{{ lookup('env', 'BACKEND_IMAGE') }}"
    frontend_image: "{{ lookup('env', 'FRONTEND_IMAGE') }}"

  tasks:
    - name: Create ProjectX folder
      command: mkdir -p /projectX && cd /projectX 

    - name: Clone ProjectX
      git:
        repo: https://github.com/P4dr4/ProjectX.git
        dest: /projectX

    # - name: Clone ProjextXB
    #   git:
    #     repo: https://github.com/P4dr4/projectXB.git
    #     dest: projectX/projectXB
    
    # - name: Clone ProjextXF
    #   git:
    #     repo: https://github.com/P4dr4/projectXF.git
    #     dest: /projectX/projectXF

    - name: Docker Login
      command: docker login -u {{ lookup('env', 'DOCKER_USERNAME') }} -p {{ lookup('env', 'DOCKER_PASSWORD') }}    

    - name: Build Backend Image
      command: docker build -t {{ backend_image }} /projectX/projectXB
      args:
        chdir: /projectX/projectXB

    - name: Build Frontend Image
      command: docker build -t {{ frontend_image }} /projectX/projectXF
      args:
        chdir: /projectX/projectXF
    
    - name: Docker-Compose Up
      command: docker-compose -f /projectX/docker-compose.yml up -d
      args:
        chdir: /projectX